version: "2"

services:
  consul:
    image: consul:latest
    ports:
      - "8500:8500"

  geolocation-1:
    image: manjesh80/geolocation:v5.4
    ports:
      - "8081"
    environment:
      GEOLOCATION_SERVICE_PORT: "8081"

  geolocation-2:
    image: manjesh80/geolocation:v5.4
    ports:
      - "8082"
    environment:
      GEOLOCATION_SERVICE_PORT: "8082"

  geolocation-consul-lb:
    image: manjesh80/geolocation-consul-lb:latest
    ports:
      - "8899:8899"

  
      