version: "2"

services:
  graphite:
    image: hopsoft/graphite-statsd
    ports:
      - "8100:80"
      - "2003:2003"
      - "2004:2004"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"